const hotels = [
  {
    location_id: "2554775",
    name: "Cape Dara Resort",
    latitude: "12.954279",
    longitude: "100.88316",
    num_reviews: "1211",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/06/63/b8/68/cape-dara-resort.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/06/63/b8/68/cape-dara-resort.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/06/63/b8/68/cape-dara-resort.jpg",
          height: "1333",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/06/63/b8/68/cape-dara-resort.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/06/63/b8/68/cape-dara-resort.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2014-08-16T05:11:27-0400",
      caption: "Walala Pool",
      id: "107198568",
      helpful_votes: "40",
      published_date: "2014-08-16T05:11:27-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.026375770568848",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "1",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#1 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "resort",
    subcategory_type_label: "Resort",
    distance: "1.6970467006798888",
    distance_string: null,
    bearing: "northwest",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$",
    price: "$110 - $172",
    hotel_class: "2",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "2cecdde4-95f9-4fd6-9f6d-b6dfc9c3940e",
  },
  {
    location_id: "14782317",
    name: "U Jomtien Pattaya",
    latitude: "12.865678",
    longitude: "100.892975",
    num_reviews: "363",
    timezone: "Asia/Bangkok",
    location_string: "Jomtien Beach, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/14/d7/ab/7f/swimming-pool.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/14/d7/ab/7f/swimming-pool.jpg",
          height: "50",
        },
        original: {
          width: "6720",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/14/d7/ab/7f/swimming-pool.jpg",
          height: "4480",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/14/d7/ab/7f/swimming-pool.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/14/d7/ab/7f/swimming-pool.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2018-09-27T23:37:27-0400",
      caption: "Swimming Pool",
      id: "349678463",
      helpful_votes: "8",
      published_date: "2018-09-27T23:37:27-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.394307613372803",
    ranking_geo: "Jomtien Beach",
    ranking_geo_id: "3366878",
    ranking_position: "2",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#2 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "4.764450408459723",
    distance_string: null,
    bearing: "south",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$55 - $86",
    hotel_class: "3",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "fc4c7227-0d2d-4b9c-9d52-18d4eddf0086",
  },
  {
    location_id: "808279",
    name: "Pinnacle Grand Jomtien Resort",
    latitude: "12.850933",
    longitude: "100.90245",
    num_reviews: "678",
    timezone: "Asia/Bangkok",
    location_string: "Jomtien Beach, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/29/0f/d7/38/pinnacle-grand-jomtien.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/29/0f/d7/38/pinnacle-grand-jomtien.jpg",
          height: "50",
        },
        original: {
          width: "2048",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/29/0f/d7/38/pinnacle-grand-jomtien.jpg",
          height: "1195",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/29/0f/d7/38/pinnacle-grand-jomtien.jpg",
          height: "321",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/29/0f/d7/38/pinnacle-grand-jomtien.jpg",
          height: "146",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-05-10T00:42:02-0400",
      caption: "",
      id: "688903992",
      helpful_votes: "0",
      published_date: "2023-05-10T00:42:02-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.973282814025879",
    ranking_geo: "Jomtien Beach",
    ranking_geo_id: "3366878",
    ranking_position: "3",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#3 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "resort",
    subcategory_type_label: "Resort",
    distance: "5.780883295188834",
    distance_string: null,
    bearing: "south",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$32 - $58",
    hotel_class: "3",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "498c0f44-e332-4d2b-b40f-a82ef35fa14c",
  },
  {
    location_id: "299782",
    name: "Avani Pattaya Resort",
    latitude: "12.928896",
    longitude: "100.879295",
    num_reviews: "2578",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/2a/48/47/e0/avani-sea-view-corner.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/2a/48/47/e0/avani-sea-view-corner.jpg",
          height: "50",
        },
        original: {
          width: "1024",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/2a/48/47/e0/avani-sea-view-corner.jpg",
          height: "576",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/2a/48/47/e0/avani-sea-view-corner.jpg",
          height: "309",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/2a/48/47/e0/avani-sea-view-corner.jpg",
          height: "141",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-09-08T17:07:24-0400",
      caption: "Avani Sea View Corner Suite Balcony Sunset",
      id: "709380064",
      helpful_votes: "0",
      published_date: "2023-09-08T17:07:24-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.474475860595703",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "4",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#4 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "resort",
    subcategory_type_label: "Resort",
    distance: "1.310782690384489",
    distance_string: null,
    bearing: "west",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$",
    price: "$95 - $141",
    hotel_class: "5",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [
        {
          value:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=299782&from=api&area=&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaTleyty1qIGoxSRuQOs7KgLTGytArfzgKmye_AWzgIuoH1N3Bz_p5E9ODGlPXTWMA&bapid=1&cs=1c73e97a03246d990ad30da18f8d45e44",
          label: "Hotel website",
          type: "url",
        },
      ],
    },
    special_offers: {
      desktop: [],
      mobile: [
        {
          headline: "Your Suite Your Way",
          url: "https://www.tripadvisor.com/ShowSpecialOffer-a_d.299782-a_offer.9156838-a_trafficSource.ba",
          offerless_click_tracking_url:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=299782&from=api&area=OID:9156838%7COT:4&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=SOIM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaTleyty1qIGoxSRuQOs7KjKayhJyxD8WKy0SuMhaPIFlueCQQZxri5k0HxuUvupDA&cs=18858ed3d137ec917f89910ca41687a81",
        },
      ],
    },
    listing_key: "128c159a-4097-4416-8309-1c745e4f28d1",
  },
  {
    location_id: "307267",
    name: "Royal Cliff Beach Terrace Pattaya",
    latitude: "12.923232",
    longitude: "100.85942",
    num_reviews: "426",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/29/7e/e9/42/feeling-peckish-during.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/29/7e/e9/42/feeling-peckish-during.jpg",
          height: "50",
        },
        original: {
          width: "4096",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/29/7e/e9/42/feeling-peckish-during.jpg",
          height: "2734",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/29/7e/e9/42/feeling-peckish-during.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/29/7e/e9/42/feeling-peckish-during.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-06-17T04:17:28-0400",
      caption:
        "Feeling peckish during your swim? Just come right up and grab your favourite cocktails and snacks, or try our tasty homemade ice creams at the Sky Aquarium Pool & Bar, without ever having to leave the pool!",
      id: "696183106",
      helpful_votes: "11",
      published_date: "2023-06-17T04:17:28-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.415024280548096",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "5",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#5 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "resort",
    subcategory_type_label: "Resort",
    distance: "2.7067454365551264",
    distance_string: null,
    bearing: "west",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$",
    price: "$96 - $137",
    hotel_class: "5",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "e1cd47b9-9bc6-40bf-a46b-b2329ca2a277",
  },
  {
    location_id: "8776727",
    name: "Centra by Centara Maris Resort Jomtien",
    latitude: "12.866008",
    longitude: "100.896576",
    num_reviews: "1324",
    timezone: "Asia/Bangkok",
    location_string: "Jomtien Beach, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/29/14/a2/13/swimming-pool-3.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/29/14/a2/13/swimming-pool-3.jpg",
          height: "50",
        },
        original: {
          width: "2715",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/29/14/a2/13/swimming-pool-3.jpg",
          height: "1810",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/29/14/a2/13/swimming-pool-3.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/29/14/a2/13/swimming-pool-3.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-05-11T21:25:46-0400",
      caption: "Swimming Pool 3",
      id: "689218067",
      helpful_votes: "0",
      published_date: "2023-05-11T21:25:46-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.437828540802002",
    ranking_geo: "Jomtien Beach",
    ranking_geo_id: "3366878",
    ranking_position: "6",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#6 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "4.730870063188042",
    distance_string: null,
    bearing: "south",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$32 - $52",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "069cc854-7c21-48c3-84ed-ffa194802017",
  },
  {
    location_id: "15184164",
    name: "Grande Centre Point Pattaya",
    latitude: "12.950231",
    longitude: "100.88932",
    num_reviews: "194",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/14/fb/b6/28/deluxe-family-connecting.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/14/fb/b6/28/deluxe-family-connecting.jpg",
          height: "50",
        },
        original: {
          width: "1280",
          url: "https://media-cdn.tripadvisor.com/media/photo-m/1280/14/fb/b6/28/deluxe-family-connecting.jpg",
          height: "925",
        },
        large: {
          width: "1024",
          url: "https://media-cdn.tripadvisor.com/media/photo-w/14/fb/b6/28/deluxe-family-connecting.jpg",
          height: "740",
        },
        medium: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/14/fb/b6/28/deluxe-family-connecting.jpg",
          height: "398",
        },
      },
      is_blessed: false,
      uploaded_date: "2018-10-08T23:07:05-0400",
      caption: "",
      id: "352040488",
      helpful_votes: "0",
      published_date: "2018-10-08T23:07:05-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.023366928100586",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "7",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#7 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.2390875443372196",
    distance_string: null,
    bearing: "northwest",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$84 - $117",
    hotel_class: "5",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "07632761-269d-4312-8dee-36a544405f10",
  },
  {
    location_id: "23195854",
    name: "Amethyst Hotel Pattaya",
    latitude: "12.927503",
    longitude: "100.88324",
    num_reviews: "35",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/26/b2/cb/7f/infinity-edge-pool-on.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/26/b2/cb/7f/infinity-edge-pool-on.jpg",
          height: "50",
        },
        original: {
          width: "7500",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/26/b2/cb/7f/infinity-edge-pool-on.jpg",
          height: "5000",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/26/b2/cb/7f/infinity-edge-pool-on.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/26/b2/cb/7f/infinity-edge-pool-on.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2022-10-26T10:34:56-0400",
      caption: "Infinity Edge Pool on the rooftop with the city view",
      id: "649251711",
      helpful_votes: "1",
      published_date: "2022-10-26T10:34:56-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.7118701934814453",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "8",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#8 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.097376295169751",
    distance_string: null,
    bearing: "southwest",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$51 - $73",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [
        {
          value:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=23195854&from=api&area=&slot=2&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkYeaWtkx0sZ7mNKigsNWMdxecQocVHhDKT--9c99BiMeKp2dCR0cxqY7Q9j2rF0o5Q&bapid=2&cs=1d3e200fcb3349baca6c6b41bc0ffd734",
          label: "Hotel website",
          type: "url",
        },
      ],
    },
    special_offers: {
      desktop: [],
      mobile: [
        {
          headline: "Direct Booking Offer",
          url: "https://www.tripadvisor.com/ShowSpecialOffer-a_d.23195854-a_offer.9897251-a_trafficSource.ba",
          offerless_click_tracking_url:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=23195854&from=api&area=OID:9897251%7COT:4&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=SOIM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkYeaWtkx0sZ7mNKigsNWMdyRPRLg9Y8osHGLLoyzR5QiATe34ogU-g5B6_3_QicZ3g&cs=1c4f76f238880ade8b35764cb5ac74570",
        },
      ],
    },
    listing_key: "e608e9b9-d0f7-422d-81bc-c0f4dee95ea9",
  },
  {
    location_id: "5040667",
    name: "Siam@Siam Design Hotel Pattaya",
    latitude: "12.945731",
    longitude: "100.88885",
    num_reviews: "2183",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/29/07/9a/57/siam-siam-design-hotel.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/29/07/9a/57/siam-siam-design-hotel.jpg",
          height: "50",
        },
        original: {
          width: "2545",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/29/07/9a/57/siam-siam-design-hotel.jpg",
          height: "1818",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/29/07/9a/57/siam-siam-design-hotel.jpg",
          height: "393",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/29/07/9a/57/siam-siam-design-hotel.jpg",
          height: "179",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-05-07T22:03:39-0400",
      caption: "",
      id: "688364119",
      helpful_votes: "1",
      published_date: "2023-05-07T22:03:39-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.490737438201904",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "9",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#9 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "0.9940347397589426",
    distance_string: null,
    bearing: "northwest",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$45 - $80",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [
        {
          value:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=5040667&from=api&area=&slot=3&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaTleyty1qIGoxSRuQOs7KhjytiLFZ6l2FpxJs08IDTTGfUDW0NfRCb5bjREQPAokA&bapid=3&cs=16d44e0f19a68b7c977729f2698c472b3",
          label: "Hotel website",
          type: "url",
        },
      ],
    },
    special_offers: {
      desktop: [],
      mobile: [
        {
          headline: "PIMP YOUR STAY",
          url: "https://www.tripadvisor.com/ShowSpecialOffer-a_d.5040667-a_offer.9968729-a_trafficSource.ba",
          offerless_click_tracking_url:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=5040667&from=api&area=OID:9968729%7COT:12&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=SOIM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaTleyty1qIGoxSRuQOs7Kic55iDY2FC7JSDvHEGjOfPI-WUqAJDIbYxs0IrZbyFOA&cs=1d20cfafaafd476d6493b19417fa85a74",
        },
      ],
    },
    listing_key: "024c65b0-8cdc-4647-b4cc-5f9d98fb7c97",
  },
  {
    location_id: "24052547",
    name: "Grande Centre Point Space Pattaya",
    latitude: "12.953053",
    longitude: "100.88829",
    num_reviews: "53",
    timezone: "Asia/Bangkok",
    location_string: "Na Kluea, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/2a/30/5c/db/space-premium-with-onsen.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/2a/30/5c/db/space-premium-with-onsen.jpg",
          height: "50",
        },
        original: {
          width: "600",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/2a/30/5c/db/space-premium-with-onsen.jpg",
          height: "400",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/2a/30/5c/db/space-premium-with-onsen.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/2a/30/5c/db/space-premium-with-onsen.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-08-28T19:16:51-0400",
      caption: "Space Premium With Onsen",
      id: "707812571",
      helpful_votes: "1",
      published_date: "2023-08-28T19:16:51-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.3940348625183105",
    ranking_geo: "Na Kluea",
    ranking_geo_id: "21316764",
    ranking_position: "10",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#10 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.4444788888650038",
    distance_string: null,
    bearing: "northwest",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$",
    price: "$134 - $219",
    hotel_class: "2",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "7cf6a744-f77e-41c2-8f66-5d0df8e5fef7",
  },
  {
    location_id: "15220571",
    name: "Centre Point Hotel Pattaya",
    latitude: "12.962568",
    longitude: "100.909744",
    num_reviews: "96",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/27/57/bd/5c/centre-point-hotel-pattaya.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/27/57/bd/5c/centre-point-hotel-pattaya.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/27/57/bd/5c/centre-point-hotel-pattaya.jpg",
          height: "1335",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/27/57/bd/5c/centre-point-hotel-pattaya.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/27/57/bd/5c/centre-point-hotel-pattaya.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2022-12-13T05:31:52-0500",
      caption: "",
      id: "660061532",
      helpful_votes: "0",
      published_date: "2022-12-13T05:31:52-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.4188098907470703",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "11",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#11 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.1062076143098714",
    distance_string: null,
    bearing: "north",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$38 - $51",
    hotel_class: "5",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "1a46e87c-e11b-401d-8b78-6edbc1039d3d",
  },
  {
    location_id: "9463224",
    name: "Veranda Resort Pattaya Na Jomtien - MGallery",
    latitude: "12.859207",
    longitude: "100.89663",
    num_reviews: "502",
    timezone: "Asia/Bangkok",
    location_string: "Jomtien Beach, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/29/36/52/de/other.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/29/36/52/de/other.jpg",
          height: "50",
        },
        original: {
          width: "346",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/29/36/52/de/other.jpg",
          height: "260",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/29/36/52/de/other.jpg",
          height: "413",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/29/36/52/de/other.jpg",
          height: "188",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-05-20T01:44:56-0400",
      caption: "Other",
      id: "691426014",
      helpful_votes: "0",
      published_date: "2023-05-20T01:44:56-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.245225429534912",
    ranking_geo: "Jomtien Beach",
    ranking_geo_id: "3366878",
    ranking_position: "12",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#12 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "resort",
    subcategory_type_label: "Resort",
    distance: "5.201136043609663",
    distance_string: null,
    bearing: "south",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$59 - $133",
    hotel_class: "5",
    hotel_class_attribution:
      "This property is classified according to Accor Hotels.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "7f29ef5a-4d19-4916-9eac-7c2ace53e156",
  },
  {
    location_id: "12862206",
    name: "Mytt Beach Hotel",
    latitude: "12.945284",
    longitude: "100.88659",
    num_reviews: "957",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/13/8e/06/58/skyline-from-swimming.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/13/8e/06/58/skyline-from-swimming.jpg",
          height: "50",
        },
        original: {
          width: "2048",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/13/8e/06/58/skyline-from-swimming.jpg",
          height: "1154",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/13/8e/06/58/skyline-from-swimming.jpg",
          height: "310",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/13/8e/06/58/skyline-from-swimming.jpg",
          height: "141",
        },
      },
      is_blessed: true,
      uploaded_date: "2018-07-02T23:33:34-0400",
      caption: "Skyline from Swimming Pool",
      id: "328074840",
      helpful_votes: "16",
      published_date: "2018-07-02T23:33:34-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.629878520965576",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "13",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#13 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.072188333835995",
    distance_string: null,
    bearing: "northwest",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$62 - $93",
    hotel_class: "5",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "a0feefcf-69af-42a2-b294-7d3db033a383",
  },
  {
    location_id: "661467",
    name: "Bella Villa Prima Hotel",
    latitude: "12.944666",
    longitude: "100.88767",
    num_reviews: "410",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/05/e1/c9/7c/bella-villa-prima-hotel.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/05/e1/c9/7c/bella-villa-prima-hotel.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/05/e1/c9/7c/bella-villa-prima-hotel.jpg",
          height: "1333",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/05/e1/c9/7c/bella-villa-prima-hotel.jpg",
          height: "366",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/05/e1/c9/7c/bella-villa-prima-hotel.jpg",
          height: "166",
        },
      },
      is_blessed: true,
      uploaded_date: "2014-05-18T05:48:56-0400",
      caption: "Deluxe Room",
      id: "98683260",
      helpful_votes: "3",
      published_date: "2014-05-18T05:48:56-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.6466503143310547",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "14",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#14 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "0.9904121711589755",
    distance_string: null,
    bearing: "northwest",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$22 - $34",
    hotel_class: "3",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "c05d040c-6412-4589-9355-76da028d4c6d",
  },
  {
    location_id: "21294008",
    name: "The Gems Mining Pool Villa Pattaya",
    latitude: "12.947436",
    longitude: "100.931625",
    num_reviews: "63",
    timezone: "Asia/Bangkok",
    location_string: "Nong Prue, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1d/25/b1/73/the-gems-mining-pool.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1d/25/b1/73/the-gems-mining-pool.jpg",
          height: "50",
        },
        original: {
          width: "1500",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1d/25/b1/73/the-gems-mining-pool.jpg",
          height: "1000",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1d/25/b1/73/the-gems-mining-pool.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1d/25/b1/73/the-gems-mining-pool.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2021-06-14T22:19:31-0400",
      caption: "Lobby Entrance",
      id: "489009523",
      helpful_votes: "0",
      published_date: "2021-06-14T22:19:31-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.884845495223999",
    ranking_geo: "Nong Prue",
    ranking_geo_id: "11891445",
    ranking_position: "15",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#15 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.445874834778958",
    distance_string: null,
    bearing: "east",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$",
    price: "$105 - $163",
    hotel_class: "5",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "602efb50-b79b-4d9b-b136-bbd9f9f045a3",
  },
  {
    location_id: "23956350",
    name: "The Quba Boutique Hotel Pattaya by Compass Hospitality",
    latitude: "12.937475",
    longitude: "100.89067",
    num_reviews: "51",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/2a/2e/80/a5/the-quba-boutique-hotel.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/2a/2e/80/a5/the-quba-boutique-hotel.jpg",
          height: "50",
        },
        original: {
          width: "6240",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/2a/2e/80/a5/the-quba-boutique-hotel.jpg",
          height: "4160",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/2a/2e/80/a5/the-quba-boutique-hotel.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/2a/2e/80/a5/the-quba-boutique-hotel.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-08-28T05:04:57-0400",
      caption: "",
      id: "707690661",
      helpful_votes: "0",
      published_date: "2023-08-28T05:04:57-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.260698318481445",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "16",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#16 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "0.532243019055676",
    distance_string: null,
    bearing: "northwest",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$23 - $37",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "e147d152-8111-48d0-b7d2-f2d99d7d9c29",
  },
  {
    location_id: "6390812",
    name: "Amari Pattaya",
    latitude: "12.948326",
    longitude: "100.88559",
    num_reviews: "2056",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/29/07/be/1b/exterior.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/29/07/be/1b/exterior.jpg",
          height: "50",
        },
        original: {
          width: "800",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/29/07/be/1b/exterior.jpg",
          height: "450",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/29/07/be/1b/exterior.jpg",
          height: "309",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/29/07/be/1b/exterior.jpg",
          height: "141",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-05-07T22:39:49-0400",
      caption: "Exterior",
      id: "688373275",
      helpful_votes: "0",
      published_date: "2023-05-07T22:39:49-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.566859722137451",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "17",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#17 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.272130325479773",
    distance_string: null,
    bearing: "northwest",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$",
    price: "$109 - $156",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [
        {
          value:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=6390812&from=api&area=&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaTleyty1qIGoxSRuQOs7KhZ9zc11dNEE8MMAhaxrkPrMK2z99bX3dER-kzNvlogIA&bapid=1&cs=1f0c5e449b87745fd5dd0d84413d0b814",
          label: "Hotel website",
          type: "url",
        },
      ],
    },
    special_offers: {
      desktop: [],
      mobile: [
        {
          headline: "Save Up to 35% for Your Exploration to Remember",
          url: "https://www.tripadvisor.com/ShowSpecialOffer-a_d.6390812-a_offer.10601715-a_trafficSource.ba",
          offerless_click_tracking_url:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=6390812&from=api&area=OID:10601715%7COT:2&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=SOIM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaTleyty1qIGoxSRuQOs7KinsUSPy0LpziNl-v6YLW2YL1VMqKj8pDq74C1YN-_JOQ&cs=1a7d1c829b17859785b29bae1cd3eb870",
        },
      ],
    },
    listing_key: "1765a4bc-3352-455f-b6de-3dee714b59d3",
  },
  {
    location_id: "1191092",
    name: "Pattaya Park Beach Resort",
    latitude: "12.906242",
    longitude: "100.86259",
    num_reviews: "475",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/08/33/03/fc/outdoor-swimming-pool--v7305255.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/08/33/03/fc/outdoor-swimming-pool--v7305255.jpg",
          height: "50",
        },
        original: {
          width: "2600",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/08/33/03/fc/outdoor-swimming-pool--v7305255.jpg",
          height: "1733",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/08/33/03/fc/outdoor-swimming-pool--v7305255.jpg",
          height: "450",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/08/33/03/fc/outdoor-swimming-pool--v7305255.jpg",
          height: "205",
        },
      },
      is_blessed: true,
      uploaded_date: "2015-04-24T11:10:29-0400",
      caption: "The Outdoor Swimming Pool at the Pattaya Park Beach Resort",
      id: "137561084",
      helpful_votes: "5",
      published_date: "2015-06-27T11:26:43-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.7230260372161865",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "18",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#18 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "resort",
    subcategory_type_label: "Resort",
    distance: "3.075699677764615",
    distance_string: null,
    bearing: "southwest",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$26 - $35",
    hotel_class: "3",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "e8bb7379-1900-40fb-aa75-26b3282ee0cd",
  },
  {
    location_id: "2337192",
    name: "Red Planet Pattaya",
    latitude: "12.944705",
    longitude: "100.8886",
    num_reviews: "826",
    timezone: "Asia/Bangkok",
    location_string: "Na Kluea, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/11/fc/32/13/red-planet-pattaya.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/11/fc/32/13/red-planet-pattaya.jpg",
          height: "50",
        },
        original: {
          width: "1200",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/11/fc/32/13/red-planet-pattaya.jpg",
          height: "800",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/11/fc/32/13/red-planet-pattaya.jpg",
          height: "366",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/11/fc/32/13/red-planet-pattaya.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2018-02-07T02:21:02-0500",
      caption: "",
      id: "301740563",
      helpful_votes: "2",
      published_date: "2018-02-07T02:21:02-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.977518320083618",
    ranking_geo: "Na Kluea",
    ranking_geo_id: "21316764",
    ranking_position: "19",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#19 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "0.9498155383097827",
    distance_string: null,
    bearing: "northwest",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$13 - $22",
    hotel_class: "3",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "c2517add-bd3a-4d61-b4b4-6d7be136b82a",
  },
  {
    location_id: "11883435",
    name: "Unique Regency Hotel",
    latitude: "12.913057",
    longitude: "100.8635",
    num_reviews: "77",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/0e/44/67/87/kly-unique-pattaya.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/0e/44/67/87/kly-unique-pattaya.jpg",
          height: "50",
        },
        original: {
          width: "1500",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/0e/44/67/87/kly-unique-pattaya.jpg",
          height: "1000",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/0e/44/67/87/kly-unique-pattaya.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/0e/44/67/87/kly-unique-pattaya.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2017-01-27T02:21:55-0500",
      caption: "",
      id: "239363975",
      helpful_votes: "2",
      published_date: "2017-01-27T05:22:15-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.4167189598083496",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "20",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#20 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.748869418702276",
    distance_string: null,
    bearing: "southwest",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$19 - $26",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "937cb7bb-ae43-461c-b224-8190bd431321",
  },
  {
    location_id: "1020072",
    name: "The Zign Hotel",
    latitude: "12.9713",
    longitude: "100.8954",
    num_reviews: "477",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1b/1e/2f/e9/the-zign-hotel.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1b/1e/2f/e9/the-zign-hotel.jpg",
          height: "50",
        },
        original: {
          width: "5464",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1b/1e/2f/e9/the-zign-hotel.jpg",
          height: "3640",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1b/1e/2f/e9/the-zign-hotel.jpg",
          height: "366",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1b/1e/2f/e9/the-zign-hotel.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2020-03-09T00:06:10-0400",
      caption: "Hotel's bird eye view",
      id: "454963177",
      helpful_votes: "1",
      published_date: "2020-03-09T00:06:10-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.4544081687927246",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "21",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#21 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.5586474708040665",
    distance_string: null,
    bearing: "north",
    rating: "3.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$49 - $74",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "d8406155-cd5c-44e2-864d-9ff4d50c5b97",
  },
  {
    location_id: "10679180",
    name: "Beston Pattaya",
    latitude: "12.92125",
    longitude: "100.88365",
    num_reviews: "61",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/0d/8d/a6/91/hotel-beston-pattaya.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/0d/8d/a6/91/hotel-beston-pattaya.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/0d/8d/a6/91/hotel-beston-pattaya.jpg",
          height: "1500",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/0d/8d/a6/91/hotel-beston-pattaya.jpg",
          height: "413",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/0d/8d/a6/91/hotel-beston-pattaya.jpg",
          height: "188",
        },
      },
      is_blessed: true,
      uploaded_date: "2016-11-07T05:00:55-0500",
      caption: "",
      id: "227387025",
      helpful_votes: "9",
      published_date: "2016-11-07T05:00:55-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.208333730697632",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "22",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#22 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.322578225345436",
    distance_string: null,
    bearing: "southwest",
    rating: "3.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$16 - $22",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "44689e97-1ce1-462b-9e52-f6280ae6943a",
  },
  {
    location_id: "23325172",
    name: "La Miniera Pool Villas Pattaya",
    latitude: "12.947745",
    longitude: "100.93258",
    num_reviews: "49",
    timezone: "Asia/Bangkok",
    location_string: "Nong Prue, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/29/d6/63/71/three-bedroom-villa-suite.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/29/d6/63/71/three-bedroom-villa-suite.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/29/d6/63/71/three-bedroom-villa-suite.jpg",
          height: "1333",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/29/d6/63/71/three-bedroom-villa-suite.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/29/d6/63/71/three-bedroom-villa-suite.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-07-23T19:14:56-0400",
      caption: "Three-Bedroom Villa Suite ",
      id: "701916017",
      helpful_votes: "0",
      published_date: "2023-07-23T19:14:56-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.911898374557495",
    ranking_geo: "Nong Prue",
    ranking_geo_id: "11891445",
    ranking_position: "23",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#23 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.5135167682117703",
    distance_string: null,
    bearing: "east",
    rating: "5.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$$$",
    price: "$173 - $236",
    hotel_class: "2",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [
        {
          value:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=23325172&from=api&area=&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkYeaWtkx0sZ7mNKigsNWMdz8bSyxZ0ZD-n52GV0MdYQfwx_W83vn3HMBB88iAhtCiA&bapid=1&cs=1c4fcc0d7ccefb1f785e62dbf8ce3a52e",
          label: "Hotel website",
          type: "url",
        },
      ],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "a9a42d51-7394-41f4-b539-384f20a20d44",
  },
  {
    location_id: "7052649",
    name: "Lemon Grass Retreat",
    latitude: "12.8446",
    longitude: "100.90816",
    num_reviews: "15",
    timezone: "Asia/Bangkok",
    location_string: "Jomtien Beach, Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/10/52/63/77/lemon-grass-retreat.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/10/52/63/77/lemon-grass-retreat.jpg",
          height: "50",
        },
        original: {
          width: "960",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/10/52/63/77/lemon-grass-retreat.jpg",
          height: "640",
        },
        large: {
          width: "960",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/10/52/63/77/lemon-grass-retreat.jpg",
          height: "640",
        },
        medium: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/10/52/63/77/lemon-grass-retreat.jpg",
          height: "367",
        },
      },
      is_blessed: true,
      uploaded_date: "2017-08-18T03:53:49-0400",
      caption: "",
      id: "273834871",
      helpful_votes: "1",
      published_date: "2017-08-18T03:53:49-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.08396315574646",
    ranking_geo: "Jomtien Beach",
    ranking_geo_id: "3366878",
    ranking_position: "24",
    ranking_denominator: "3134",
    ranking_category: "bb",
    ranking: "#24 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "small_hotel",
    subcategory_type_label: "Small Hotel",
    distance: "6.249191914048503",
    distance_string: null,
    bearing: "south",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$23 - $29",
    hotel_class: "3",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "3251921f-3eed-46c6-a37a-9ec29694043f",
  },
  {
    location_id: "1653641",
    name: "Pullman Pattaya Hotel G",
    latitude: "12.962361",
    longitude: "100.88517",
    num_reviews: "3120",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/27/9e/d5/53/exterior-view.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/27/9e/d5/53/exterior-view.jpg",
          height: "50",
        },
        original: {
          width: "1024",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/27/9e/d5/53/exterior-view.jpg",
          height: "768",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/27/9e/d5/53/exterior-view.jpg",
          height: "413",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/27/9e/d5/53/exterior-view.jpg",
          height: "188",
        },
      },
      is_blessed: true,
      uploaded_date: "2022-12-26T16:47:21-0500",
      caption: "Exterior view",
      id: "664720723",
      helpful_votes: "2",
      published_date: "2022-12-26T16:47:21-0500",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.188584327697754",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "25",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#25 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.116647966882848",
    distance_string: null,
    bearing: "northwest",
    rating: "4.0",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$77 - $106",
    hotel_class: "5",
    hotel_class_attribution:
      "This property is classified according to Accor Hotels.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "870e45fe-e212-40a7-9f63-7f1f8106d6ee",
  },
  {
    location_id: "14917765",
    name: "Golden Tulip Pattaya Beach Resort",
    latitude: "12.970123",
    longitude: "100.8842",
    num_reviews: "387",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/28/55/f3/5a/golden-tulip-pattaya.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/28/55/f3/5a/golden-tulip-pattaya.jpg",
          height: "50",
        },
        original: {
          width: "1397",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/28/55/f3/5a/golden-tulip-pattaya.jpg",
          height: "931",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/28/55/f3/5a/golden-tulip-pattaya.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/28/55/f3/5a/golden-tulip-pattaya.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-02-24T08:45:43-0500",
      caption: "Golden Tulip Pattaya Beach Resort",
      id: "676721498",
      helpful_votes: "0",
      published_date: "2023-02-24T08:45:43-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.548211097717285",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "26",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#26 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "2.638633666467765",
    distance_string: null,
    bearing: "north",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$48 - $70",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "e359b47e-91d9-4cd9-9a5c-b26a7ec7d6e4",
  },
  {
    location_id: "17379163",
    name: "Hotel Amber Pattaya",
    latitude: "12.930957",
    longitude: "100.88759",
    num_reviews: "308",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/1c/47/9d/33/hotel-amber-pattaya.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/1c/47/9d/33/hotel-amber-pattaya.jpg",
          height: "50",
        },
        original: {
          width: "3000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/1c/47/9d/33/hotel-amber-pattaya.jpg",
          height: "2000",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/1c/47/9d/33/hotel-amber-pattaya.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/1c/47/9d/33/hotel-amber-pattaya.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2020-11-05T01:37:47-0500",
      caption: "",
      id: "474455347",
      helpful_votes: "11",
      published_date: "2020-11-05T01:37:47-0500",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.268023490905762",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "27",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#27 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "0.7348209502271552",
    distance_string: null,
    bearing: "west",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$33 - $49",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "a062f7f0-949e-41e9-95be-683163d8fc3e",
  },
  {
    location_id: "553435",
    name: "Siam Bayshore",
    latitude: "12.923741",
    longitude: "100.86944",
    num_reviews: "2279",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/28/95/71/32/deluxe-suite.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/28/95/71/32/deluxe-suite.jpg",
          height: "50",
        },
        original: {
          width: "664",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/28/95/71/32/deluxe-suite.jpg",
          height: "386",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/28/95/71/32/deluxe-suite.jpg",
          height: "320",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/28/95/71/32/deluxe-suite.jpg",
          height: "145",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-03-22T18:06:09-0400",
      caption: "deluxe suite",
      id: "680882482",
      helpful_votes: "3",
      published_date: "2023-03-22T18:06:09-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.305891513824463",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "28",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#28 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "resort",
    subcategory_type_label: "Resort",
    distance: "2.055538499601163",
    distance_string: null,
    bearing: "west",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$64 - $100",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [
        {
          value:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=553435&from=api&area=&slot=2&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkaTleyty1qIGoxSRuQOs7KhpoiIqxJJf9U_4IyzsdQr-b5H0Mh6qtzKemtYJMPvZUg&bapid=2&cs=10d5a2cfc1f007a44fa265fbd9ed1762d",
          label: "Hotel website",
          type: "url",
        },
      ],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "543da69e-394c-4dc7-940d-5d4042cf478b",
  },
  {
    location_id: "19977889",
    name: "OZO North Pattaya",
    latitude: "12.949189",
    longitude: "100.88549",
    num_reviews: "256",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/29/08/c9/4c/pool-overview.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/29/08/c9/4c/pool-overview.jpg",
          height: "50",
        },
        original: {
          width: "4369",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/29/08/c9/4c/pool-overview.jpg",
          height: "2200",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/29/08/c9/4c/pool-overview.jpg",
          height: "277",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/29/08/c9/4c/pool-overview.jpg",
          height: "126",
        },
      },
      is_blessed: true,
      uploaded_date: "2023-05-08T02:52:46-0400",
      caption: "Pool Overview",
      id: "688441676",
      helpful_votes: "1",
      published_date: "2023-05-08T02:52:46-0400",
      user: null,
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "4.488060474395752",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "29",
    ranking_denominator: "3134",
    ranking_category: "hotel",
    ranking: "#29 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "hotel",
    subcategory_type_label: "Hotel",
    distance: "1.3221640806460755",
    distance_string: null,
    bearing: "northwest",
    rating: "4.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$61 - $81",
    hotel_class: "4",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [
        {
          value:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=19977889&from=api&area=&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=CLM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkYeaWtkx0sZ7mNKigsNWMdx6WWDyRo7V0tLByUNyG2zf9Enkdb5XFlN2wWJV6TIXzw&bapid=1&cs=137afe1f45c06ff3ba7d9706ca56d7cd4",
          label: "Hotel website",
          type: "url",
        },
      ],
    },
    special_offers: {
      desktop: [],
      mobile: [
        {
          headline: "Unpack.Endless.Fun with Up to 35% Discount",
          url: "https://www.tripadvisor.com/ShowSpecialOffer-a_d.19977889-a_offer.10601723-a_trafficSource.ba",
          offerless_click_tracking_url:
            "https://www.tripadvisor.com/Commerce?p=TABAIndependentHotels&src=0&geo=19977889&from=api&area=OID:10601723%7COT:2&slot=1&matchID=1&oos=0&cnt=1&silo=30355&bucket=875169&ubucket=875169&nrank=1&crank=1&clt=SOIM&tm=274968924&managed=false&capped=false&gosox=5_3Y6UYwwGjgw_c7hEwIkYeaWtkx0sZ7mNKigsNWMdw0pGKHgFWb6VI3Vr6WAA-3OTGac1UylJbtOddfDWngjA&cs=16dcadb7d7063e39e036d75732f10cf41",
        },
      ],
    },
    listing_key: "9967bc4d-696f-4790-a736-a9a0fe98978b",
  },
  {
    location_id: "7785162",
    name: "Balihai Bay Pattaya",
    latitude: "12.923953",
    longitude: "100.86713",
    num_reviews: "76",
    timezone: "Asia/Bangkok",
    location_string: "Pattaya, Chonburi Province",
    photo: {
      images: {
        small: {
          width: "150",
          url: "https://media-cdn.tripadvisor.com/media/photo-l/07/8a/6e/ad/balihai-bay-pattaya.jpg",
          height: "150",
        },
        thumbnail: {
          width: "50",
          url: "https://media-cdn.tripadvisor.com/media/photo-t/07/8a/6e/ad/balihai-bay-pattaya.jpg",
          height: "50",
        },
        original: {
          width: "2000",
          url: "https://media-cdn.tripadvisor.com/media/photo-o/07/8a/6e/ad/balihai-bay-pattaya.jpg",
          height: "1333",
        },
        large: {
          width: "550",
          url: "https://media-cdn.tripadvisor.com/media/photo-s/07/8a/6e/ad/balihai-bay-pattaya.jpg",
          height: "367",
        },
        medium: {
          width: "250",
          url: "https://media-cdn.tripadvisor.com/media/photo-f/07/8a/6e/ad/balihai-bay-pattaya.jpg",
          height: "167",
        },
      },
      is_blessed: true,
      uploaded_date: "2015-03-19T03:49:34-0400",
      caption: "Swimming Pool",
      id: "126512813",
      helpful_votes: "2",
      published_date: "2015-03-24T10:10:47-0400",
      user: {
        user_id: null,
        member_id: "0",
        type: "user",
      },
    },
    awards: [],
    preferred_map_engine: "default",
    autobroaden_type: "category_integrated",
    autobroaden_label: "Pattaya Places to Stay",
    raw_ranking: "3.159738063812256",
    ranking_geo: "Pattaya",
    ranking_geo_id: "293919",
    ranking_position: "30",
    ranking_denominator: "3134",
    ranking_category: "bb",
    ranking: "#30 Best Value of 3,134 places to stay in Pattaya",
    subcategory_type: "small_hotel",
    subcategory_type_label: "Small Hotel",
    distance: "2.196888344230488",
    distance_string: null,
    bearing: "west",
    rating: "3.5",
    is_closed: false,
    is_long_closed: false,
    price_level: "$",
    price: "$32 - $54",
    hotel_class: "3",
    hotel_class_attribution: "This property is classified according to Giata.",
    business_listings: {
      desktop_contacts: [],
      mobile_contacts: [],
    },
    special_offers: {
      desktop: [],
      mobile: [],
    },
    listing_key: "f049f5f7-7760-4668-8b3d-51816d4460d2",
  },
];

export default hotels;
